### ISSUE TITLE
Problem to add ngx-translate module

### ISSUE THREAD

**Issue by ibadass** [nikosanif/angular-authentication#4]
Hi,

First of all, nice work, it's a very good project. So thanks !

I'm trying to implement ngx-translate module in the app, but I encounter several problems.

I import TranslateModule in app.module.ts like that: 
```
TranslateModule.forRoot({
      defaultLanguage: 'fr',
      loader: {
          provide: TranslateLoader,
          useFactory: HttpLoaderFactory,
          deps: [HttpClient]
      },
      isolate: false,
      extend: true
    })
```
And the HttpLoaderFactory :
```
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

```

Then in core.module.ts and auth.module.ts, I import translate module as: 
```
TranslateModule.forChild({
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpClient]
  },
  isolate: false,
  extend: true
}),
```

And I have my language file (fr.json, en.json) in a folder in src/assets/i18n/.

## Current Behavior
I have a 404 error when I start the app on my language files. And I don't understand why.

## Expected Behavior
In an other angular app, I do not have problem to add translate module and my json are correctly read.

Do you have any ideas to correct this issue ?

Thank you.
ibadass

**Comment by nikosanif** [comment]
Hey @ibadass! Thanks for your issue report and the detailed description! 💯 

I tried to reproduce your issue and you are right, I got a `404` response. This happens because we use a fake API with [`angular-in-memory-web-api`](https://github.com/angular/angular/tree/master/packages/misc/angular-in-memory-web-api). So, there are 2 solutions:

- You can either remove the fake API initialization by removing the [current line](https://github.com/nikosanif/angular-authentication/blob/68b4811b2d0685438d29154574afce53310f1df3/src/app/core/core.module.ts#L30). This means that you have your own real server for Auth API.
- Or you can use the `passThruUnknownUrl: true` option and will forward unrecognized requests. Replace the [current line](https://github.com/nikosanif/angular-authentication/blob/68b4811b2d0685438d29154574afce53310f1df3/src/app/core/core.module.ts#L30) with `HttpClientInMemoryWebApiModule.forRoot(FakeApiService, { passThruUnknownUrl: true })`.

Please let me know if it worked for you.

**Comment by ibadass** [comment]
Thank you very much ! It's ok now !
I use my own backend server, so I choose your first solution.
