### ISSUE TITLE
Retrieve error message

### ISSUE THREAD

**Issue by ibadass** [nikosanif/angular-authentication#5]
Hello (it's me again...),

I'm having some trouble retrieving error messages stored in the hasLoginError$ store.
I want to get the error message and code (response from my API service) when the login action failed and display it in my html file, to replace the actual message (Ooops! The login details are incorrect. ).

I'm new on angular, and haven't been able to do this.

Can you help me for this?

Thanks in advance.
ibadass

**Comment by nikosanif** [comment]
Hi @ibadass, you need to create a new variable in the auth store in order to keep the error message. 

In more detail, when the response throws the error you will be able to assign it in the aforementioned variable using the `catchError()` operator at [this line](https://github.com/nikosanif/angular-authentication/blob/682ec097e9881ab8ce8459aa355521e5ecc681c8/src/app/auth/store/auth.effects.ts#L24). 

You should follow similar approach for the response status. In case you need to keep the status both for success and failure you should use the `finalize()` operator. Also, you have to consider setting `observe: 'response'` to your request (see [official docs](https://angular.io/guide/http)) in order to get the response status.

I hope you find this useful, let me know if you have any further questions.
